# ProvToolbox interoperability tests
#
# This job assumes the following packages have been installed (these
# are provided by the Travis CI build environment,
# http://docs.travis-ci.com/user/ci-environment:
#
# git
# curl
# python 2.7
# graphviz 
# maven
# openjdk-7-jdk

language: python

python:
  - 2.7

addons:
  apt:
    packages:
    - graphviz
    - rpm
    - libxml2-utils
    - zlib1g-dev
    - libxslt1-dev

before_install:
  - echo "Getting test harness..."
  - git clone https://github.com/mikej888/interop-test-harness
  - cd interop-test-harness
  - git checkout package
  - python setup.py install
  - cd ..
  - echo "Getting test cases..."
  - git clone https://github.com/prov-suite/testcases
  - echo "Getting ProvToolbox source..."
  - git clone -b development https://github.com/lucmoreau/ProvToolbox.git ProvToolbox
  - cd ProvToolbox
  - mvn clean install -DskipTests
  - export PATH=$PATH:PWD/toolbox/target/appassembler/bin
  - provconvert -version
  - cd ..

script: 
  - nosetests prov_interop.interop_tests.test_provtoolbox > log.txt
